Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/12/2022
Var
cont: inteiro
idade: inteiro
Inicio
para cont de 1 ate 4 faca
escreval ("digite a idade",cont)
leia(idade)
escreval("idade digitada:",idade)
 fimpara
Fimalgoritmo